### PR TITLE
Add the CEC-HDMI on/off trick

### PR DESCRIPTION
**Pull request by stan69b**
Solution for old tv sets that do not support wake on lan

** I've not made an .md file in a while, you may need to fix some line returns and stuff if you don't mind. Feel free to edit anything I wrote if you feel the need :) **

### CODE REVIEW

**Comment by AntonioMeireles** [comment]
@stan69b, 

[sorry lag] much thanks for this, will help a ton of ppl. will merge as is, and edit a bit. 

Thanks!

**Comment by AntonioMeireles** [comment]
@stan69b can you give me permission to commit to your PR branch please :-) (per https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) 

Thanks in advance!

**Comment by stan69b** [comment]
The « allow maintainer to edit ... » checkbox is checked, it’s my first pull request, i have to say I’m a little bit lost xD I’m looking into it at the moment ;)

**Comment by stan69b** [comment]
I added you to the repo as a collaborator, does it help ?

**Comment by AntonioMeireles** [comment]
@stan69b 

never mind. edited and committed from my side ( https://github.com/AntonioMeireles/homebridge-vieramatic/commit/7011790264881262f5bc0b0c2bdebbf074bee931 ). 

at sight, and after yet another read 0 just one thing left with room to improvement, imho. 

> **You can disable on your homebridge device the system that changes your tv input to that of the homebridge device if you want, google is your friend**.

can you elaborate on this ?

**Comment by stan69b** [comment]
Sorry for the inconvenient with my lack of knowledge on PR, guess I'll have to make more PR to get better at them :D

**Comment by AntonioMeireles** [comment]
@stan69b 

updated tip per your feedback. i think it's fine by now. will close if you have no objections!

many thanks for your patience!

**Comment by stan69b** [comment]
Nicely done :) way better explained than what I did, thanks for spending the time on it ;) You can close this PR.

Have a great day

**Comment by AntonioMeireles** [comment]
merged manually by https://github.com/AntonioMeireles/homebridge-vieramatic/commit/7011790264881262f5bc0b0c2bdebbf074bee931 and https://github.com/AntonioMeireles/homebridge-vieramatic/commit/17fb6c069dd57ad9159fc964e26c5501bdfa72cb. 

many thanks to @stan69b hard work and patience! . closing.

**Pull request closed without merging**
